/*
	framework de mission du CORP
	http://www.corp-arma.fr
*/

#define PARAJUMP_CLASSIC_DIALOG_IDD 423430

#define PARAJUMP_CLASSIC_LIST_IDC 10
#define PARAJUMP_CLASSIC_ALTITUDE_IDC 11
#define PARAJUMP_CLASSIC_MAP_IDC 12
#define PARAJUMP_CLASSIC_CLOSE_IDC 13
#define PARAJUMP_CLASSIC_JUMP_IDC 14
